version: '3'
services:
  api:
    build: .
    ports:
      - "8888:8888"
    working_dir: /usr/src/app
  web:
    image: dkra4741/tools-for-live
    ports: 
      - "3000:80" # host port:container export port
    links:
      - api
