version: '3'
services:
  api:
    image: dkra4741/tools-for-live-api
    ports:
      - "8888:8888"
    # volumes:
    #   - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    links:
      - web
  web:
    image: dkra4741/tools-for-live
    ports: 
      - "80:80" # host port:container export port

  
